services:
  - type: web
    name: ai-financial-scenarios-api
    env: python
    buildCommand: pip install -r server/requirements.txt
    startCommand: uvicorn server.app:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: ANTHROPIC_API_KEY
        sync: false   # add in Render dashboard
      - key: OPENAI_API_KEY
        sync: false
      - key: AZURE_OPENAI_API_KEY
        sync: false
      - key: AZURE_OPENAI_ENDPOINT
        sync: false
      - key: FRONTEND_ORIGIN
        value: https://ai-financial-scenarios.vercel.app
